version: '3.8'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
    networks:
      - app-network

  server:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      PRODUCTION: 1
    volumes:
      - ./:/app
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    # driver: bridge
