version: '1'
services:
  db:
    image: mysql:5-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
    networks:
      - app-network
    ports:
      - "3307:3306" # this should be removed in production for security reasons

  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      PRODUCTION: 1
    volumes:
      - ./:/app
    networks:
      - app-network
    depends_on:
      - db
    links:
      - db
    
networks:
  app-network:
    #driver: bridge
